import { createClient } from '@supabase/supabase-js'
import Link from 'next/link'
import { notFound } from 'next/navigation'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  {
    global: {
      fetch: (url, options = {}) =>
        fetch(url, { ...options, next: { revalidate: 3600 } }),
    },
  }
)

const stateAbbreviations: Record<string, string> = {
  'alabama': 'AL', 'alaska': 'AK', 'arizona': 'AZ', 'arkansas': 'AR', 'california': 'CA',
  'colorado': 'CO', 'connecticut': 'CT', 'delaware': 'DE', 'florida': 'FL', 'georgia': 'GA',
  'hawaii': 'HI', 'idaho': 'ID', 'illinois': 'IL', 'indiana': 'IN', 'iowa': 'IA',
  'kansas': 'KS', 'kentucky': 'KY', 'louisiana': 'LA', 'maine': 'ME', 'maryland': 'MD',
  'massachusetts': 'MA', 'michigan': 'MI', 'minnesota': 'MN', 'mississippi': 'MS', 'missouri': 'MO',
  'montana': 'MT', 'nebraska': 'NE', 'nevada': 'NV', 'new-hampshire': 'NH', 'new-jersey': 'NJ',
  'new-mexico': 'NM', 'new-york': 'NY', 'north-carolina': 'NC', 'north-dakota': 'ND', 'ohio': 'OH',
  'oklahoma': 'OK', 'oregon': 'OR', 'pennsylvania': 'PA', 'rhode-island': 'RI', 'south-carolina': 'SC',
  'south-dakota': 'SD', 'tennessee': 'TN', 'texas': 'TX', 'utah': 'UT', 'vermont': 'VT',
  'virginia': 'VA', 'washington': 'WA', 'west-virginia': 'WV', 'wisconsin': 'WI', 'wyoming': 'WY'
}

export default async function CityPage({ params }: any) {
  const { state, city } = await params

  // Unknown state slug → hard 404
  if (!stateAbbreviations[state]) {
    notFound()
  }

  const stateUpper = stateAbbreviations[state]
  const cityFormatted = city.split('-').map((word: string) =>
    word.charAt(0).toUpperCase() + word.slice(1)
  ).join(' ')
  const slug = `${state}/${city}`

  const [{ data: guideData }, { data: restaurants }] = await Promise.all([
    supabase.from('city_pages').select('*').eq('slug', slug).maybeSingle(),
    supabase
      .from('listings')
      .select('*')
      .eq('state', stateUpper)
      .ilike('city', cityFormatted)
      .order('google_rating', { ascending: false }),
  ])

  // Valid state but no listings yet → show informative page (200, not 404)
  if (!restaurants || restaurants.length === 0) {
    return <EmptyCityPage state={stateUpper} city={cityFormatted} stateSlug={state} />
  }

  if (guideData) {
    return <CuratedCityGuide data={guideData} restaurants={restaurants} />
  }

  return <AutoGeneratedCityPage state={stateUpper} city={cityFormatted} restaurants={restaurants} />
}

function EmptyCityPage({ state, city, stateSlug }: { state: string; city: string; stateSlug: string }) {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-gradient-to-br from-blue-600 via-purple-600 to-pink-600 text-white py-20">
        <div className="max-w-7xl mx-auto px-4">
          <nav className="text-sm mb-6 opacity-90">
            <Link href="/" className="hover:underline">Home</Link>
            {' / '}
            <Link href="/directory" className="hover:underline">Directory</Link>
            {' / '}
            <Link href={`/states/${stateSlug}`} className="hover:underline">{state}</Link>
            {' / '}
            {city}
          </nav>
          <h1 className="text-5xl md:text-6xl font-bold mb-6">Filipino Food in {city}, {state}</h1>
          <p className="text-xl md:text-2xl max-w-3xl opacity-95">
            We're growing our directory — help us add Filipino restaurants in {city}.
          </p>
        </div>
      </div>
      <div className="max-w-3xl mx-auto px-4 py-16 text-center">
        <div className="bg-white rounded-xl shadow-lg p-10">
          <p className="text-5xl mb-6">🗺️</p>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">
            No listings yet for {city}, {state}
          </h2>
          <p className="text-gray-600 mb-8 leading-relaxed">
            We don't have any Filipino restaurants, grocery stores, or food businesses
            listed for {city} yet. Know a great spot? Be the first to add it!
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/add-business"
              className="bg-yellow-500 hover:bg-yellow-400 text-gray-900 font-bold px-8 py-3 rounded-lg transition-colors"
            >
              Add a Business
            </Link>
            <Link
              href="/directory"
              className="bg-white border-2 border-gray-300 hover:border-blue-500 hover:text-blue-600 text-gray-700 font-bold px-8 py-3 rounded-lg transition-colors"
            >
              Browse All Listings
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}

function CuratedCityGuide({ data, restaurants }: any) {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-gradient-to-br from-blue-600 via-purple-600 to-pink-600 text-white py-20">
        <div className="max-w-7xl mx-auto px-4">
          <nav className="text-sm mb-6 opacity-90">
            <Link href="/">Home</Link> / <Link href="/guides">Guides</Link> / {data.city}
          </nav>
          <h1 className="text-5xl md:text-7xl font-bold mb-6">{data.city}, {data.state_full}</h1>
          <p className="text-xl md:text-2xl max-w-3xl opacity-95">{data.intro_tagline}</p>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 py-16">
        <div className="grid lg:grid-cols-3 gap-12">
          <div className="lg:col-span-2 space-y-12">
            <section className="bg-white rounded-xl shadow-lg p-8">
              <p className="text-gray-700 leading-relaxed mb-4">{data.intro_paragraph_1}</p>
              <p className="text-gray-700 leading-relaxed">{data.intro_paragraph_2}</p>
            </section>

            {data.community_places && data.community_places.length > 0 && (
              <section className="bg-white rounded-xl shadow-lg p-8">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">🏘️ Where Community Gathers</h2>
                <div className="space-y-4">
                  {data.community_places.map((place: any, idx: number) => (
                    <div key={idx} className="border-l-4 border-blue-500 pl-4">
                      <h3 className="font-bold text-lg text-gray-900">{place.name}</h3>
                      <p className="text-gray-600">{place.description}</p>
                    </div>
                  ))}
                </div>
              </section>
            )}

            {data.food_highlights && data.food_highlights.length > 0 && (
              <section className="bg-white rounded-xl shadow-lg p-8">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">🍽️ What You'll Notice in the Food</h2>
                <ul className="space-y-3">
                  {data.food_highlights.map((item: any, idx: number) => (
                    <li key={idx} className="flex items-start gap-3">
                      <span className="text-blue-600 text-xl">•</span>
                      <span className="text-gray-700">{typeof item === 'string' ? item : item.text}</span>
                    </li>
                  ))}
                </ul>
              </section>
            )}

            {data.featured_restaurants && data.featured_restaurants.length > 0 && (
              <section className="bg-white rounded-xl shadow-lg p-8">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">⭐ Most Memorable Bites</h2>
                <div className="grid md:grid-cols-2 gap-6">
                  {data.featured_restaurants.map((restaurant: any, idx: number) => (
                    <Link
                      key={idx}
                      href={`/directory?search=${encodeURIComponent(restaurant.name)}`}
                      className="border border-gray-200 rounded-lg p-6 hover:shadow-lg hover:border-blue-500 transition-all"
                    >
                      <h3 className="font-bold text-xl text-gray-900 mb-2 hover:text-blue-600">
                        {restaurant.name}
                      </h3>
                      <p className="text-gray-600 mb-3">{restaurant.description}</p>
                      {restaurant.signature_dish && (
                        <p className="text-sm text-blue-600">
                          <strong>Try:</strong> {restaurant.signature_dish}
                        </p>
                      )}
                    </Link>
                  ))}
                </div>
              </section>
            )}

            {restaurants && restaurants.length > 0 && (
              <section className="bg-white rounded-xl shadow-lg p-8">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">📍 All Filipino Restaurants in {data.city}</h2>
                <div className="grid md:grid-cols-2 gap-4">
                  {restaurants.map((restaurant: any) => (
                    <Link
                      key={restaurant.id}
                      href={`/listings/${restaurant.slug}`}
                      className="border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow hover:border-blue-500"
                    >
                      <h3 className="font-bold text-gray-900 hover:text-blue-600 mb-1">{restaurant.name}</h3>
                      <p className="text-sm text-gray-600 mb-2">{restaurant.category_primary}</p>
                      {restaurant.google_rating && (
                        <div className="flex items-center gap-1">
                          <span className="text-yellow-500">★</span>
                          <span className="font-medium text-sm">{restaurant.google_rating}</span>
                          {restaurant.google_total_ratings && (
                            <span className="text-gray-500 text-xs">({restaurant.google_total_ratings})</span>
                          )}
                        </div>
                      )}
                    </Link>
                  ))}
                </div>
              </section>
            )}
          </div>

          <div className="lg:col-span-1">
            <div className="sticky top-4 space-y-6">
              <div className="bg-yellow-50 border-2 border-yellow-300 rounded-xl p-6">
                <h3 className="font-bold text-lg text-gray-900 mb-4">Quick Facts</h3>
                <div className="space-y-3 text-sm">
                  <div>
                    <p className="text-gray-600">Filipino Population</p>
                    <p className="font-bold text-gray-900">{data.filipino_population}</p>
                  </div>
                  <div>
                    <p className="text-gray-600">Migration History</p>
                    <p className="text-gray-700">{data.migration_history}</p>
                  </div>
                  {data.cultural_tidbit && (
                    <div>
                      <p className="text-gray-600">Did You Know?</p>
                      <p className="text-gray-700">{data.cultural_tidbit}</p>
                    </div>
                  )}
                </div>
              </div>

              <div className="bg-gradient-to-br from-blue-50 to-purple-50 border-2 border-blue-300 rounded-xl p-6 text-center">
                <h3 className="font-bold text-lg text-gray-900 mb-3">Know a great spot?</h3>
                <p className="text-sm text-gray-700 mb-4">Help us keep this guide complete and accurate.</p>
                <Link href="/add-business" className="block bg-yellow-500 hover:bg-yellow-400 text-gray-900 px-4 py-2 rounded-lg font-bold transition-colors">
                  Add a Restaurant
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function AutoGeneratedCityPage({ state, city, restaurants }: any) {
  const totalRestaurants = restaurants.length
  const categories = [...new Set(restaurants.map((r: any) => r.category_primary))].filter(Boolean) as string[]
  const avgRating = restaurants.filter((r: any) => r.google_rating).length > 0
    ? (restaurants.reduce((sum: number, r: any) => sum + (r.google_rating || 0), 0) / restaurants.filter((r: any) => r.google_rating).length).toFixed(1)
    : null

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-gradient-to-br from-blue-600 via-purple-600 to-pink-600 text-white py-20">
        <div className="max-w-7xl mx-auto px-4">
          <nav className="text-sm mb-6 opacity-90">
            <Link href="/" className="hover:underline">Home</Link>
            {' / '}
            <Link href="/directory" className="hover:underline">Directory</Link>
            {' / '}
            <Link href={`/states/${state.toLowerCase()}`} className="hover:underline">{state}</Link>
            {' / '}
            {city}
          </nav>
          <h1 className="text-5xl md:text-7xl font-bold mb-6">Filipino Food in {city}, {state}</h1>
          <p className="text-xl md:text-2xl max-w-3xl opacity-95">
            Discover {totalRestaurants} authentic Filipino {totalRestaurants === 1 ? 'restaurant' : 'restaurants'} serving traditional and modern Filipino cuisine.
          </p>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 py-16">
        <div className="grid lg:grid-cols-3 gap-12">
          <div className="lg:col-span-2 space-y-12">
            <section className="bg-white rounded-xl shadow-lg p-8">
              <h2 className="text-3xl font-bold text-gray-900 mb-6">About Filipino Food in {city}</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                {city}, {state} is home to {totalRestaurants} Filipino {totalRestaurants === 1 ? 'restaurant' : 'restaurants'}. 
                Discover authentic dishes from across the Philippines, from classic comfort food like adobo and pancit to regional specialties that taste like home.
              </p>
              <p className="text-gray-700 leading-relaxed">
                From family-owned turo-turo spots to modern Filipino fusion concepts, the Filipino food scene in {city} brings 
                together traditional recipes, fresh ingredients, and the warm hospitality Filipino cuisine is known for.
              </p>
            </section>

            {categories.length > 0 && (
              <section className="bg-white rounded-xl shadow-lg p-8">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">What You'll Find</h2>
                <div className="flex flex-wrap gap-3">
                  {categories.map((cat: string) => (
                    <span key={cat} className="bg-blue-100 text-blue-800 px-4 py-2 rounded-full text-sm font-medium">
                      {cat}
                    </span>
                  ))}
                </div>
              </section>
            )}

            <section className="bg-white rounded-xl shadow-lg p-8">
              <h2 className="text-3xl font-bold text-gray-900 mb-6">📍 All Filipino Restaurants in {city}</h2>
              <div className="grid md:grid-cols-2 gap-4">
                {restaurants.map((restaurant: any) => (
                  <Link
                    key={restaurant.id}
                    href={`/listings/${restaurant.slug}`}
                    className="border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow hover:border-blue-500"
                  >
                    <h3 className="font-bold text-gray-900 hover:text-blue-600 mb-1">{restaurant.name}</h3>
                    <p className="text-sm text-gray-600 mb-2">{restaurant.category_primary}</p>
                    {restaurant.google_rating && (
                      <div className="flex items-center gap-1">
                        <span className="text-yellow-500">★</span>
                        <span className="font-medium text-sm">{restaurant.google_rating}</span>
                        <span className="text-gray-500 text-xs">({restaurant.google_reviews_count} reviews)</span>
                      </div>
                    )}
                    <p className="text-xs text-gray-500 mt-2">
                      {restaurant.address_street}
                    </p>
                  </Link>
                ))}
              </div>
            </section>
          </div>

          <div className="lg:col-span-1">
            <div className="sticky top-4 space-y-6">
              <div className="bg-blue-50 border-2 border-blue-300 rounded-xl p-6">
                <h3 className="font-bold text-lg text-gray-900 mb-4">Quick Stats</h3>
                <div className="space-y-3 text-sm">
                  <div>
                    <p className="text-gray-600">Total Filipino Restaurants</p>
                    <p className="font-bold text-2xl text-gray-900">{totalRestaurants}</p>
                  </div>
                  {avgRating && (
                    <div>
                      <p className="text-gray-600">Average Rating</p>
                      <p className="font-bold text-2xl text-gray-900">★ {avgRating}</p>
                    </div>
                  )}
                  <div>
                    <p className="text-gray-600">Categories</p>
                    <p className="text-gray-700">{categories.length} types of Filipino businesses</p>
                  </div>
                </div>
              </div>

              <div className="bg-gradient-to-br from-yellow-50 to-orange-50 border-2 border-yellow-300 rounded-xl p-6 text-center">
                <h3 className="font-bold text-lg text-gray-900 mb-3">Know a great spot in {city}?</h3>
                <p className="text-sm text-gray-700 mb-4">Help fellow Filipino food lovers discover authentic restaurants.</p>
                <Link href="/add-business" className="block bg-yellow-500 hover:bg-yellow-400 text-gray-900 px-4 py-2 rounded-lg font-bold transition-colors">
                  Add a Restaurant
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}